### ISSUE TITLE
Goal: Prepare new domain application form prototype for QA

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/getgov#255]
At the end of this sprint our goal is to prepare a prototype of a domain submission request for QA. In order to accomplish this goal, our tasks are:  

- [x] Link up #222 and #223 after #257 lands
- [ ] #262 
- [ ] #251 (adds the application state transitions discussed to the backend model)
- [x] #252 
- [x] #231 
- [x] #253 
- [ ] **This is unlocks a lot of other work** #260 
- [x] #261
- [ ] #263 
- [ ] Implement styles for [option A](https://www.figma.com/proto/ninNjo0bTg7XfB4mvTp4hG/GetGov%2FWireframes?page-id=1007%3A4676&node-id=1022%3A4952&viewport=1193%2C-651%2C0.36&scaling=min-zoom&starting-point-node-id=1022%3A4952&show-proto-sidebar=1&hide-ui=1)
    - [ ] #259  (take from the home.dotgov.gov site currently) 
- [ ] Create a QA/Bug Bash document
