### ISSUE TITLE
Sprint Goal: Launch plan for beta.get.gov

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#595]
A/C: A complete plan for launching beta.get.gov

- [x] #601 
- [x] Approvals from EA? Any other approvals for beta launch in place or determined
- [x] #618 Reverse/anti-SEO plan - @igorkorenfeld has some helpful comments from the beta.ada.gov team. 
- [x] #619 
- [x] #620 (Dependent on 618 and 619, will also need to account for needed by the cloud.gov team) 
- [ ] #341 (Dependent on 618, 620, will also need to account for time needed by the search.gov)
- [x] #612
- [x] #543 should also be involved in this so that we have a clean auth pattern on the django site
