### ISSUE TITLE
Decision and supporting research on use of Django admin

### ISSUE THREAD

**Issue by loganmeetsworld** [cisagov/getgov#597]
- [ ] A/C: An ADR documenting the decision to use Django admin for the user experience for managing domain applications and support requests by analysts.

Considerations: security, user experience, customization. 

See previous research here: https://github.com/cisagov/getgov/issues/14

**Comment by rachidatecs** [comment]
Consolidating past and current discussions. Checked items have been researched and prototyped in https://github.com/cisagov/getgov/tree/rjm/admin-research

**Technical** (Previous research: https://github.com/cisagov/getgov/issues/14):

- [x] Investigate and document options for role-based access control (RBAC) from the CISA admin perspective
- [ ] From Add Domain model #277. There is seemingly a bug with FSMField and choices: admin says "Select a valid choice. False is not one of the available choices."
- [ ] From Add Domain model #277. Admin does not work with FSMFields if protected=True. (Neil: https://github.com/gadventures/django-fsm-admin)
- [ ] Testing: Is it easy enough to make a TestCase that makes an admin user, uses force_login, and loads one or more of these admin pages?

**UX** (Research goals previously identified by Igor):

- [x] Location of search box / search capabilities
- [x] Ability to run reports (Reports that CISA needs: https://github.com/cisagov/getgov/issues/143)
- [x] Ability to export data (Rachid did basic research and will document)
- [x] Sorting ability
- [x] (less important) Ability to theme

**Security** (Ops requirement Qs for CISA)

- [ ] Is there a CISA requirement to be on a certain network? (Logan: we think not)
- [ ] How much we need to limit permissions via obscurity vs actually limiting (consider accidental vs malicious scenarios) - (related to technical point 1, above)?
- [ ] What sort of monitoring and logging do we need for security purposes?

**Comment by h-m-f-t** [comment]
Though there are some logging tasks still to perform, I think we've completed this task. PR https://github.com/cisagov/getgov/pull/743 is where we added the ADR. 

Is there anything left? cc: @kitsushadow / @PaulKuykendall
