### ISSUE TITLE
Setup robots.txt and meta tags for beta.get.gov

### ISSUE THREAD

**Issue by igorkorenfeld** [cisagov/getgov#618]
A/C:
- [ ] robots.txt file added to the getgov-home repo
- [ ] robots.txt **disallows** commercial search engines (e.g. google and bing)
- [ ] Add meta tags to disallow indexing
- [ ] robots.txt allows serach.gov's indexer 
 
As noted in #341 we will want to prevent commercial search engines from crawling the site before it is ready for launch, while allowing search.gov to index it so that the search functions work. Search.gov has [documentation](https://search.gov/indexing/robotstxt.html) on the robots.txt file 

More documentation on robots.txt at https://www.robotstxt.org/robotstxt.html

Additionally we should add meta tags to prevent indexing as noted in the [documentation on discoverability](https://search.gov/indexing/how-search-engines-index-content-better-discoverability.html#robots).
