### ISSUE TITLE
EPIC: Administrative Reporting

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/getgov#936]
### Issue Description

As an analyst and administrator of the .gov program, I need access to various reports in order to effectively perform my job(s). These reports may involve data from different sources, but I want to have access to them from a logical, central place.

Things to do
- [x] #143 
- [x] Discovery - Determine the actual problem/need to refine solution.
- [x] #938 
- [x] Data Engineering - what are the authoritative sources to provide this data (post-transition)

### Additional Context

FOR MVP: Per the work done in #143, There are four reports required for initial launch:

- [ ] 3 similar reports #996 
  -  **Current Active Domains - ALL domains, or "current-full.csv"**: all .gov domains with metadata in CSV. These reports are published online, which we then [grab](https://github.com/cisagov/dotgov-data/blob/main/.github/workflows/flat.yml) to do git scraping.
  - **Current Active Domains - Federal Only, or "current-federal.csv"**: A federal-only subset of current-full.
  - **Domains by Type** - This is the report that's actually the source for current-federal and -full. It includes all metadata about a domain, including contacts. CSV.
- [ ] Domain Growth report #998 
  * This report is key to quarterly reporting. Given a data range, show all domain activations/deletions and summarize them numerically. This is currently an export and the summary is represented on the page.
- [ ] Publishing the current-federal and current-full.csvs 
  * See #1075 

(There is _post-MVP enhancement work_ for these reports at #998 and #999.)

### Issue Links

#143

**Comment by PaulKuykendall** [comment]
MVP - Decision documented [here](https://github.com/cisagov/getgov/issues/143#issuecomment-1635062479)

**Comment by h-m-f-t** [comment]
Let's close this. There's follow-on tickets that have been created that will meet our initial reporting needs.
